version: '2'
services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      jh-pretix-net:
        aliases:
          - db

  redis:
    image: quay.io/sameersbn/redis:latest
    restart: unless-stopped
    networks:
      jh-pretix-net:
        aliases:
          - redis

  pretix:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./volumes/pretix-data:/data
      - ./volumes/pretix:/etc/pretix
    ports:
      - 127.0.0.1:5000:80
    networks:
      jh-pretix-net:
        aliases:
          - pretix

networks:
  jh-pretix-net:
